/**
 * The long reading of every card: a description, its upright meaning, how
 * it reads for relationships and for work, and its reversed meaning. This
 * is the guidebook page behind each face. Shown in the Codex by tier
 * (knowledge.ts), never on the card and never in a reading.
 */
export interface Lore {
  description: string;
  upright: string;
  relationships: string;
  career: string;
  reversed: string;
}

export const LORE: Record<string, Lore> = {
  // --- Major Arcana --------------------------------------------------------
  'major-0': {
    description: 'The Fool stands at the edge of a cliff with a small pack and a white rose, looking up rather than down. The card is the whole journey before it begins: innocence, trust, and a step taken on faith.',
    upright: 'Something new is asking you to begin it, and you do not yet have all the information. That is the point. Go lightly, carry only what you need, and let the road teach you what a plan could not.',
    relationships: 'A fresh start or a new person, met with an open heart and no history. Enjoy it for what it is rather than deciding already what it must become.',
    career: 'A new role, a side venture, or a leap into work you have not done before. Your inexperience is a strength here, because you will ask the questions everyone else stopped asking.',
    reversed: 'The leap taken carelessly, or not taken at all. Either you are rushing into something with your eyes shut, or fear has you frozen at the edge. Look down once, honestly, then decide.',
  },
  'major-1': {
    description: 'The Magician stands at a table laid with a wand, a cup, a sword and a coin, one hand raised to the sky and one pointed to the earth. Every tool is present. What matters is the will to use them.',
    upright: 'You have what you need. The skills, the resources and the timing are all in reach, and the only missing piece is your decision to act. Focus your intent and begin; things will move when you do.',
    relationships: 'Clear communication and real attraction. You can shape this connection with honesty and attention. Say what you want.',
    career: 'A time to show what you can do. Pitch the idea, take the lead on the project, ask for the responsibility. Your competence is visible now.',
    reversed: 'Talent without direction, or skill turned to trickery. You may be scattering your energy across too many things, or someone near you may be saying one thing and doing another. Check the sleight of hand, including your own.',
  },
  'major-2': {
    description: 'The High Priestess sits between two pillars before a veil, a scroll half hidden in her lap and a crescent moon at her feet. She knows, and she is not telling. The card is intuition, mystery and the wisdom that comes from stillness.',
    upright: 'The answer is already in you, below the surface of thought. Stop gathering opinions and listen to the quiet certainty underneath. Not everything needs to be explained to be known.',
    relationships: 'Depth, patience and unspoken understanding. Something is not yet being said, by you or by them. Let it surface in its own time rather than forcing it.',
    career: 'Trust your read of the room. Information is being withheld or has not yet come to light, and the wise move is to observe before you commit.',
    reversed: 'Intuition ignored or a secret kept too long. You may be talking yourself out of what you already sense, or letting something stay hidden that needs air. Withdrawal is not the same as wisdom.',
  },
  'major-3': {
    description: 'The Empress reclines in a field of ripening grain beside a stream, crowned with stars, a heart-shaped shield at her side. She is abundance made visible: growth, nurture, the body and the earth.',
    upright: 'Things are growing. Tend them and they will come to fruit. This is a time of comfort, creativity and care, for others and for yourself. Make something, feed someone, rest in what you have built.',
    relationships: 'Warmth, sensuality and a nurturing bond. A relationship deepening into home, or the wish for one. Fertility in the literal sense can also be meant.',
    career: 'Creative work flourishes and projects mature. Provide for your team, invest in what is taking root, and expect a harvest.',
    reversed: 'Smothering care or neglected self. Either you are giving until you are hollow, or you have stopped tending what needs you. Creative block and dependence sit here too.',
  },
  'major-4': {
    description: 'The Emperor sits on a stone throne carved with rams, armoured under his robe, holding an orb and an ankh. He is structure, authority and the order that makes things last.',
    upright: 'Take charge and build the frame. Rules, plans and boundaries are what this moment needs, and you are able to provide them. Lead with steadiness rather than force.',
    relationships: 'Stability and protection, a partner who shows up and keeps their word. The risk is control dressed as care. Steady, not rigid.',
    career: 'Authority, promotion, or the need to impose order on a messy situation. Systems and discipline pay off. A powerful figure may be watching your work.',
    reversed: 'Rigidity, domination, or the loss of control. A rule that no longer serves, a leader who bullies, or your own refusal to bend. Ask whether the structure protects people or only protects itself.',
  },
  'major-5': {
    description: 'The Hierophant sits between two pillars with two acolytes kneeling before him, keys crossed at his feet. He is tradition, teaching and the shared belief that binds a community.',
    upright: 'Look to what has worked before. A mentor, an institution or an established practice has something to offer you now. Belonging and shared values matter more than going it alone.',
    relationships: 'Commitment in its traditional forms: marriage, vows, meeting the family. A bond built on shared values and made public.',
    career: 'Learn the rules before you break them. Formal training, certification and a respected mentor serve you. Conventional paths open.',
    reversed: 'Dogma, or rebellion against it. Either you are following a form that has lost its meaning, or you are rejecting all guidance out of pride. Question the teaching, but do not throw away the lesson.',
  },
  'major-6': {
    description: 'Two figures stand beneath an angel with the sun behind it, a tree of fruit and a tree of flame on either side. The Lovers is union, and the choice that union always requires.',
    upright: 'A meaningful connection, or a decision that reveals what you truly value. Choose from alignment rather than convenience. What you say yes to here will shape more than the moment.',
    relationships: 'Real intimacy, mutual attraction and the feeling of being seen. A relationship reaching a point of commitment or a proposal of some kind.',
    career: 'A partnership or a fork in the road. Choose the work that fits your values, and the collaborator who shares them.',
    reversed: 'Disharmony, misalignment or a choice avoided. Values are pulling in different directions, or you are staying in something that no longer fits because leaving is hard. Temptation and imbalance live here.',
  },
  'major-7': {
    description: 'A warrior stands in a chariot drawn by two sphinxes, one black and one white, holding no reins. The Chariot is will, drive and victory won by holding opposing forces on one course.',
    upright: 'Move with determination. You can win this by focus and self-command, steering through opposition rather than around it. Confidence and momentum are on your side.',
    relationships: 'Taking the initiative, a relationship moving forward with purpose. Make sure both of you are pulling in the same direction.',
    career: 'Ambition rewarded. Push the project through, take the journey, chase the promotion. Discipline turns drive into results.',
    reversed: 'Drive without direction, or a stall. Aggression, scattered effort, or forces pulling you apart. Loosen your grip and check where you are actually headed.',
  },
  'major-8': {
    description: 'A woman calmly closes the jaws of a lion with her bare hands, an infinity sign above her head. Strength is not force. It is courage, patience and gentle mastery.',
    upright: 'Meet the difficulty with composure. Your inner steadiness is greater than the thing that roars at you. Compassion and quiet persistence will do what force cannot.',
    relationships: 'Patience and emotional maturity. A bond that survives hard moments because someone kept their temper and their tenderness at once.',
    career: 'Handle a difficult person or situation with calm authority. Endurance and self-control mark you out as someone to trust.',
    reversed: 'Self-doubt, raw nerves, or strength turned to domination. You may be forcing what needs coaxing, or doubting a courage you actually have. Fear of your own power sits here.',
  },
  'major-9': {
    description: 'An old figure in grey stands alone on a mountain with a staff and a lantern holding a single star. The Hermit is the withdrawal that lets you see clearly, and the light you carry for others afterwards.',
    upright: 'Step back. Solitude, reflection and honest self-examination are what this passage needs. Seek a wiser voice, or become one. The answer is found alone before it is shared.',
    relationships: 'A need for space, or a partner who needs it. Time apart for reflection can strengthen what remains, if it is chosen and not merely endured.',
    career: 'Research, study, a sabbatical, or the mentor you have been looking for. Work done quietly and thoroughly now pays later.',
    reversed: 'Isolation instead of solitude, or refusing to look inward at all. Loneliness, withdrawal from those who need you, or advice ignored. Come down the mountain when the lamp is lit.',
  },
  'major-10': {
    description: 'A great wheel turns in the clouds, marked with letters and symbols, a sphinx on top and creatures rising and falling at its rim. The Wheel of Fortune is change, cycles and the turn of luck no one controls.',
    upright: 'Something is turning in your favour. A change of luck, a new cycle, a door opening that you did not knock on. Ride it while it lasts and stay humble; the wheel keeps turning.',
    relationships: 'A turning point. Fate brings someone into your life, or moves a relationship into a new season. Accept the change rather than clinging to the last one.',
    career: 'Opportunity arrives by chance rather than by plan. Be ready to say yes. What was stuck begins to move.',
    reversed: 'The wheel turning against you, or resistance to a change that is coming regardless. Bad luck, delays, and the frustration of things outside your control. Hold on and remember that this too is a cycle.',
  },
  'major-11': {
    description: 'A crowned figure sits between two pillars holding scales in one hand and an upright sword in the other. Justice is truth, fairness and the consequence that follows every act.',
    upright: 'Things are being weighed. Act with integrity and expect to be treated the same. Decisions made now will stand, so make them with clear eyes. Legal and contractual matters resolve fairly.',
    relationships: 'Honesty and balance. A relationship asking for fairness in what each gives. Speak the truth plainly and expect it in return.',
    career: 'Contracts, negotiations and judgements. Do the right thing and document it. Accountability works in your favour.',
    reversed: 'Injustice, dishonesty or a refusal to own consequences. You may be treated unfairly, or you may be avoiding the fair result of your own choices. Blame is being misplaced.',
  },
  'major-12': {
    description: 'A man hangs upside down from a living tree by one foot, hands behind his back, a halo of light around his head. The Hanged Man is surrender, suspension and the new view that comes from letting go.',
    upright: 'Pause. This is a time to wait, to release control and to see the situation from the other way up. What looks like a loss of momentum is a change of perspective you need.',
    relationships: 'Sacrifice for another, or a relationship in limbo. Let the pause do its work rather than forcing a resolution.',
    career: 'A project on hold, or a deliberate step back. Use the time to reconsider the approach. The way forward looks different from here.',
    reversed: 'Stalling for its own sake, or resisting a surrender that would free you. Martyrdom, indecision, and a wait that has become an excuse. Either commit to the pause or end it.',
  },
  'major-13': {
    description: 'A skeleton in black armour rides a pale horse carrying a banner with a white rose, while a king lies fallen and a child offers flowers. Death is the ending that makes room. It is almost never a literal death.',
    upright: 'Something is over, and it needs to be over. Let it end cleanly, grieve what deserves grief, and turn toward what the ending makes possible. Transformation begins with clearing the ground.',
    relationships: 'The end of a relationship, or of a phase within one. What survives will be changed. Do not resuscitate what has finished.',
    career: 'A job, a role or a way of working coming to a close. Resistance prolongs the discomfort. Let the old form fall so the new one can stand.',
    reversed: 'Refusing the ending. Clinging, stagnation, a change delayed until it becomes a crisis. Fear of transformation is costing you more than the transformation would.',
  },
  'major-14': {
    description: 'An angel with one foot on land and one in water pours liquid between two cups, an unbroken stream. Temperance is balance, patience and the blending of opposites into something whole.',
    upright: 'Moderation and calm. Find the middle path, mix what seemed incompatible, and let things settle at their own pace. Healing and harmony are available if you do not rush them.',
    relationships: 'Give and take in balance. A relationship that soothes rather than stirs. Patience with each other repairs what haste damaged.',
    career: 'Cooperation and steady progress. Blend approaches, mediate between factions, and pace yourself for the long run.',
    reversed: 'Excess, imbalance and impatience. Too much of one thing, whether work, drink, control or worry. Something is out of proportion and needs to be brought back to the middle.',
  },
  'major-15': {
    description: 'A horned figure crouches on a black pedestal above two chained figures who could slip their chains if they chose. The Devil is bondage, appetite and the illusions we mistake for necessity.',
    upright: 'Look at what holds you. A habit, a fear, a dependency or a story about what you cannot do without. The chain is loose. Naming the attachment honestly is the beginning of leaving it.',
    relationships: 'Intense attraction, possessiveness or a bond that has become a trap. Passion is not the problem; losing yourself in it is.',
    career: 'Golden handcuffs, overwork, or a compromise of your values for money or status. Ask what the job is costing you beyond hours.',
    reversed: 'Breaking free. Awareness of the chain, and the first pull against it. Recovery, release, and the return of choice. The hardest step is already behind you.',
  },
  'major-16': {
    description: 'Lightning strikes a tower built on a rock, its crown flies off, and two figures fall from the windows into the dark. The Tower is sudden upheaval, the collapse of what was built on a false foundation.',
    upright: 'Something is coming down, fast. A revelation, a shock, a structure failing. It will feel like disaster and it is also a clearing. What falls could not have been fixed from inside.',
    relationships: 'A sudden rupture or a truth that changes everything. What survives will have to be rebuilt on honest ground.',
    career: 'Layoffs, a failed launch, a scandal, or an assumption exposed. Move quickly, protect what you can, and do not rebuild the same tower.',
    reversed: 'A disaster narrowly avoided, or one prolonged by resisting it. You may be holding up a wall that needs to fall, or feeling the aftershocks of a collapse you have not yet accepted.',
  },
  'major-17': {
    description: 'A woman kneels at a pool under a great star and seven smaller ones, pouring water onto the land and into the water. The Star is hope, healing and faith restored after the storm.',
    upright: 'You have come through. Now comes calm, renewal and a quiet confidence in the future. Let yourself be replenished. Inspiration returns when you stop bracing.',
    relationships: 'Healing after hurt, openness, and a hopeful new connection. Vulnerability is safe here.',
    career: 'Renewed purpose and a clearer vision. A creative period, recognition, or the sense that you are finally on the right path.',
    reversed: 'Hope worn thin. Discouragement, disconnection from what once inspired you, or a faith lost after too many storms. The star is still there; you have stopped looking up.',
  },
  'major-18': {
    description: 'A moon with a face looks down on a path between two towers, where a dog and a wolf howl and a crayfish climbs from the water. The Moon is illusion, fear, dreams and the things that move in half light.',
    upright: 'Not everything is what it seems. Anxiety, confusion and old fears are colouring the view. Go slowly, trust your instincts over the story you are telling yourself, and wait for daylight before you decide.',
    relationships: 'Uncertainty, mixed signals or something unspoken. Jealousy and projection distort what is really there. Ask rather than assume.',
    career: 'Unclear information, hidden agendas or self-doubt. Verify before you act. Creative and intuitive work benefits from this fog; decisions do not.',
    reversed: 'The fog lifting. Confusion clearing, a deception exposed, a fear seen for its true size. Or, less kindly, refusing to look at what the dark is showing you.',
  },
  'major-19': {
    description: 'A child rides a white horse beneath a huge smiling sun, sunflowers behind a wall, a red banner in hand. The Sun is joy, success, vitality and the truth in plain light.',
    upright: 'Things are good, and it is all right to say so. Confidence, warmth, success and clarity. Share what you have. This is a card of yes.',
    relationships: 'Joyful, open, uncomplicated love. Celebrations, a child, or the simple happiness of being together in the daylight.',
    career: 'Recognition, success and energy for the work. A project comes into the light and is praised. Enjoy it.',
    reversed: 'Clouds over the sun. Temporary sadness, a success that feels hollow, or optimism that has become denial. The light is not gone; it is waiting for you to come outside.',
  },
  'major-20': {
    description: 'An angel sounds a trumpet from the clouds and figures rise from their graves with arms open. Judgement is awakening, reckoning and the call to become who you were meant to be.',
    upright: 'A moment of clarity about your life so far. Forgive, decide, and answer the call. The past is understood, not erased, and the way forward is finally obvious.',
    relationships: 'Reconciliation, a relationship reassessed honestly, or a call to a deeper commitment. What was buried comes up to be resolved.',
    career: 'A turning point, a review, or a vocation revealed. Take stock, learn the lesson, and step into the larger role.',
    reversed: 'Self-doubt, harsh self-judgement, or refusing the call. You are either rehearsing old failures or ignoring what you already know you must do. Stop the trial and make the choice.',
  },
  'major-21': {
    description: 'A dancer wrapped in a sash holds two wands inside a laurel wreath, the four living creatures at the corners. The World is completion, wholeness and the journey fulfilled.',
    upright: 'A cycle completes. What you set out to do is done, and done well. Travel, achievement, integration and a sense of belonging in your own life. Celebrate before you begin again.',
    relationships: 'Fulfilment and a bond that feels whole. A relationship reaching maturity, or two lives fitting together with ease.',
    career: 'A project finished, a degree earned, a goal reached. Recognition and the sense of a chapter closing well. The next one begins from strength.',
    reversed: 'Incompletion. Loose ends, a goal almost reached, or a reluctance to close a chapter that is finished. Something needs to be brought to its end before you can move on.',
  },
  // --- Wands: fire, will, work, ambition --------------------------------------
  'wands-1': {
    description: 'A hand reaches from a cloud holding a living branch that sprouts new leaves, a castle far below. The Ace of Wands is the spark itself: raw creative energy, a new passion, the first push of a will.',
    upright: 'An idea has caught. Act on the impulse while it is hot, because this kind of energy does not keep. A creative project, a bold plan or a new enthusiasm wants to begin now.',
    relationships: 'A spark of attraction, a passionate beginning, or fresh fire in a long bond. Chemistry is strong; let it lead for a while.',
    career: 'A new venture, a job offer, or the drive to start something of your own. The energy is here; the structure can follow.',
    reversed: 'A spark that will not catch. False starts, delays, and enthusiasm that fizzles before anything is built. Find what is smothering the fire before you strike again.',
  },
  'wands-2': {
    description: 'A figure in a red robe stands on a battlement holding a globe in one hand and a staff in the other, looking out to sea. The Two of Wands is planning, discovery and the choice of a direction.',
    upright: 'You have a first success behind you and the world in your hand. Now decide where to point yourself. Plan the long road, weigh the options honestly, and prepare to leave the walls you know.',
    relationships: 'Deciding what you want from a bond, or choosing between staying comfortable and reaching for more. A long-distance element may be present.',
    career: 'Strategy and expansion. Map the next stage, consider a bigger market or a move abroad, and choose one path rather than admiring all of them.',
    reversed: 'Fear of the far road. Plans made and never left, indecision, or a safe choice made from timidity. The globe in your hand is useless if you never step off the wall.',
  },
  'wands-3': {
    description: 'A figure stands on a headland watching three ships sail out across a golden sea, three staves planted beside them. The Three of Wands is foresight, expansion and the patience of waiting for a return.',
    upright: 'What you set in motion is under way. Look further ahead than you have been, trust the ships you sent out, and prepare for what they bring back. Growth is coming from beyond your present borders.',
    relationships: 'A relationship widening its horizons: travel together, plans for the future, or a bond that stretches across distance and holds.',
    career: 'Expansion, trade, overseas opportunity. Early results confirm the plan. Keep your eye on the horizon and your feet on the shore.',
    reversed: 'Ships that do not come back. Delays, obstacles, and plans frustrated by things outside your control. Check whether you sent the right ships, or simply sent them too soon.',
  },
  'wands-4': {
    description: 'Four staves hung with garlands frame a gateway, and figures dance before a castle beyond. The Four of Wands is celebration, homecoming and the welcome that follows a milestone.',
    upright: 'A time to celebrate. A homecoming, a wedding, a housewarming, a job well done. Enjoy the stability you have built and the people who share it with you.',
    relationships: 'Commitment marked and celebrated. Moving in together, an engagement, or the feeling that a relationship has become home.',
    career: 'A milestone reached and recognised. Team harmony, a launch celebrated, a foundation secure enough to build on.',
    reversed: 'A feast with the doors shut. Tension at home, a celebration postponed, or a transition that leaves you unsettled. The garland is up but the welcome is not yet felt.',
  },
  'wands-5': {
    description: 'Five youths strike at each other with staves in a scrum that looks half like a fight and half like sport. The Five of Wands is competition, friction and the clash of wills.',
    upright: 'Everyone wants something different at once. Conflict is in the air, but it need not be destructive; it can sharpen ideas and clear the room. Compete fairly and say your piece.',
    relationships: 'Bickering, rivalry, or too many voices in one bond. Argue about the thing itself rather than about each other.',
    career: 'Competition for a role, a team pulling in different directions, or a brainstorm that turns into a brawl. Channel the energy into the work.',
    reversed: 'Conflict avoided or turned inward. Either the fight ends and cooperation returns, or resentment goes underground. Make sure peace is real and not just quiet.',
  },
  'wands-6': {
    description: 'A rider crowned with laurel carries a staff wreathed in laurel through a crowd that cheers. The Six of Wands is victory, recognition and the pride of being seen.',
    upright: 'You have won, and people know it. Accept the praise gracefully and let it carry you toward the next effort. Confidence earned is different from confidence assumed.',
    relationships: 'Being admired, or admiring. A bond you are proud to show. Make sure the parade includes them.',
    career: 'Public success, a promotion, an award. Your work is recognised. Use the moment to open the next door.',
    reversed: 'A crown too heavy, or no crown at all. Fall from favour, egotism, or success that arrives without the recognition you hoped for. Ask whose approval you were really riding for.',
  },
  'wands-7': {
    description: 'A figure on a rise holds a staff against six staves raised from below. The Seven of Wands is defiance, perseverance and the defence of a position hard won.',
    upright: 'You hold the high ground and others want it. Stand your ground with conviction. Challenges test what you have built, and meeting them makes it yours.',
    relationships: 'Defending a relationship against outside pressure, or standing up for yourself within one. Boundaries are the theme.',
    career: 'Competition for what you have, criticism of your work, or the need to justify your position. Argue your case; you are on the higher ground.',
    reversed: 'Overwhelmed. Giving up the slope, feeling outnumbered, or exhaustion from a fight that has gone on too long. Consider whether every hill is worth holding.',
  },
  'wands-8': {
    description: 'Eight staves fly in parallel across a clear sky over open country, none yet landed. The Eight of Wands is speed, movement and news on its way.',
    upright: 'Things move fast now. Messages arrive, decisions land, travel happens. Act quickly and keep your aim clear, because momentum like this does not wait.',
    relationships: 'A whirlwind: passion arriving fast, a message that changes things, or a long-distance bond drawing close.',
    career: 'Rapid progress, a flurry of communication, deadlines met in a rush. Move with it and keep your priorities in order.',
    reversed: 'Arrows falling short. Delays, miscommunication, haste that arrives nowhere. Something is being rushed or something is stuck; slow down enough to aim.',
  },
  'wands-9': {
    description: 'A bandaged figure leans on a staff, eight more planted behind like a fence, watching for the next blow. The Nine of Wands is resilience, the last watch and the will to stay standing.',
    upright: 'You are tired and you are still here. One more push is needed. Guard what you have won, keep your defences up a little longer, and know that the end of this is close.',
    relationships: 'Wariness after hurt. Walls built from old wounds. Persistence can heal this, but so can letting one guard down at a time.',
    career: 'The last stretch of a long project. Burnout is near, and so is the finish. Protect your energy and keep going.',
    reversed: 'Paranoia, fatigue, a wall guarded too long against no one. Or, at last, collapse. Ask whether the threat is real before you spend another night on the wall.',
  },
  'wands-10': {
    description: 'A figure bent under ten staves carries them alone toward a distant town. The Ten of Wands is burden, responsibility and the cost of success taken on all at once.',
    upright: 'You are carrying too much, and much of it by choice. The goal is close, but ask what could be set down or shared. Success that crushes you is not the success you wanted.',
    relationships: 'Carrying a relationship alone, or bringing your burdens home so heavily that there is no room for anything else. Share the load.',
    career: 'Overwork, too many responsibilities, the reward for competence being more work. Delegate before you drop something important.',
    reversed: 'Setting the load down, or being crushed by it. Release, delegation and relief, or a collapse that forces the question. Either way, the load changes.',
  },
  'wands-11': {
    description: 'A young figure in bright clothes holds a sprouting staff and stares at it with delight, in a desert with pyramids behind. The Page of Wands is enthusiasm, exploration and a message of fire.',
    upright: 'A new passion, a bold idea, or news that excites you. Follow the curiosity. You do not need to be an expert to begin; you need to be willing.',
    relationships: 'Flirtation, a playful new connection, or a lively message. Fun and freedom matter more than plans right now.',
    career: 'A new project, an apprenticeship, or an idea worth pitching. Enthusiasm opens doors that credentials do not.',
    reversed: 'Hasty, unfocused, all spark and no plan. Bad news, a false start, or an enthusiasm that burns out before anything is finished. Pick one thing.',
  },
  'wands-12': {
    description: 'A knight in armour with a plume of flames charges on a rearing horse, staff raised. The Knight of Wands is passion, impulse and adventure at full gallop.',
    upright: 'Go. Boldness, energy and appetite for the new carry you forward. Take the trip, make the move, start the thing. Just check the direction before you spur the horse.',
    relationships: 'Passionate, exciting, and possibly fleeting. A charismatic arrival, a whirlwind romance. Enjoy the ride while watching for the ditch.',
    career: 'Ambitious action, relocation, a bold pitch. Fortune favours the daring here, as long as daring is paired with follow-through.',
    reversed: 'Recklessness, or the charge with no one behind it. Impatience, anger, a plan abandoned halfway. Slow the horse; you can still get there.',
  },
  'wands-13': {
    description: 'A queen on a throne carved with lions holds a staff and a sunflower, a black cat at her feet. The Queen of Wands is warmth, confidence and charisma that draws people in.',
    upright: 'Take up space. Your warmth, determination and social ease can carry a room. Lead by being fully yourself, and welcome others into the light you make.',
    relationships: 'A vibrant, loyal and passionate partner, or the call to be one. Confidence is attractive; so is generosity.',
    career: 'Leadership through charisma. Networking, hosting, rallying a team. Your presence is an asset; use it deliberately.',
    reversed: 'Jealousy, a warmth turned demanding, or confidence collapsing into insecurity. A temper, a need for attention, or a spotlight hoarded. Check what the cat is watching.',
  },
  'wands-14': {
    description: 'A king in a robe of flame sits on a throne with salamanders, a staff planted beside him. The King of Wands is vision, leadership and bold command.',
    upright: 'Lead with vision. You can see further than the people around you and inspire them to go there. Be decisive, be generous with your fire, and delegate the details.',
    relationships: 'A confident, protective, sometimes overwhelming partner. Passion and loyalty, with a need for the other person to have their own fire too.',
    career: 'Entrepreneurship, senior leadership, a big-picture role. Set the direction and let others build the road.',
    reversed: 'A tyrant in flame. Impulsive, ruthless, loud, unwilling to hear anyone else. Or a vision without the discipline to carry it. Leadership that burns the people it was meant to warm.',
  },
  // --- Cups: water, feeling, love, the inner life ------------------------------
  'cups-1': {
    description: 'A hand from a cloud offers an overflowing cup, a dove descending toward it, five streams pouring into a pool of lilies. The Ace of Cups is the source of feeling: love, compassion and the heart opened.',
    upright: 'Your heart is full and something new is flowing into it. Love, creativity, forgiveness, or a spiritual opening. Receive it without measuring.',
    relationships: 'New love, a deepening of intimacy, or the birth of a family. Emotional honesty is rewarded now.',
    career: 'Work that feeds the heart. A creative beginning, a caring role, or a team where you feel genuinely welcome.',
    reversed: 'The cup spilled or sealed. Repressed feeling, emptiness, a love not returned. Something in you is blocked, and the cup cannot fill until it is unblocked.',
  },
  'cups-2': {
    description: 'Two figures exchange cups beneath a winged lion over a caduceus. The Two of Cups is partnership, mutual attraction and the meeting of equals.',
    upright: 'A connection of real mutuality. Two people, two sides, meeting as equals and choosing each other. Harmony in love, friendship or partnership.',
    relationships: 'The card of the couple. Attraction returned, a proposal, a bond that balances. If you are asking whether it is mutual, this is a yes.',
    career: 'A strong partnership or alliance. A collaborator who complements you. Contracts sealed with a handshake that means it.',
    reversed: 'Imbalance between two. Miscommunication, a breakup, or one person giving what the other does not return. The cups are no longer level.',
  },
  'cups-3': {
    description: 'Three women raise their cups together in a harvest field, dancing. The Three of Cups is friendship, celebration and shared joy.',
    upright: 'Gather your people. Community, friendship and celebration lift you now. Creative collaboration and good news shared are the theme.',
    relationships: 'Friendship as the ground of love, a celebration among friends, or the joy of belonging. Be wary only of a third party where two were meant.',
    career: 'Team success, a launch party, a creative circle. Work is better together right now.',
    reversed: 'The party gone sour. Gossip, exclusion, overindulgence, or a circle that no longer holds. Look at who is really at the table.',
  },
  'cups-4': {
    description: 'A figure sits under a tree with arms crossed, three cups before them and a fourth offered from a cloud, unnoticed. The Four of Cups is apathy, withdrawal and the gift not seen.',
    upright: 'You are bored, or disappointed, and something is being offered that you have not looked at. Reassess. The answer may already be in front of you.',
    relationships: 'Emotional distance, taking a partner for granted, or an interest you keep missing. Look up.',
    career: 'Dissatisfaction with work that is not wrong so much as stale. An opportunity is being overlooked. Contemplate, then choose.',
    reversed: 'Waking up. Renewed interest, an offer accepted, a stagnant spell ending. Or, less kindly, withdrawal deepening into avoidance.',
  },
  'cups-5': {
    description: 'A cloaked figure stands over three spilled cups, back turned to two that still stand, a bridge and a house beyond. The Five of Cups is grief, regret and the loss that fills the whole view.',
    upright: 'Something has been lost and it hurts. Grieve honestly. And when you can, turn around: two cups still stand, and the bridge home is behind you.',
    relationships: 'Heartbreak, mourning a relationship, or dwelling on what went wrong. Forgiveness, of yourself or another, is the road back.',
    career: 'A failure, a lost deal, a project that did not survive. Learn from it, then salvage what remains.',
    reversed: 'Recovery. Acceptance, moving on, a return to what is still standing. Or a grief refused, which is its own way of staying at the spilled cups.',
  },
  'cups-6': {
    description: 'A child offers a cup filled with a flower to a smaller child, in a garden of old houses. The Six of Cups is nostalgia, innocence and the kindness of the past.',
    upright: 'Memory, sweetness, and something returning from your past. A reunion, a childhood joy, or a simple act of kindness. Let the past nourish you without keeping you there.',
    relationships: 'An old flame, a childhood friend, or a relationship that feels safe and familiar. Comfort and care.',
    career: 'A return to old work, a former colleague, or the reward of a past effort. Skills from long ago prove useful.',
    reversed: 'Stuck in the past, or a past that would not let go. Naivety, clinging to what was, or an old wound reopened. The way forward is not behind you.',
  },
  'cups-7': {
    description: 'A figure faces seven cups floating in cloud, each holding something different: a crown, a serpent, a castle, jewels, a laurel, a dragon, a veiled shape. The Seven of Cups is choice, fantasy and the danger of wishing.',
    upright: 'Too many options and not enough ground. Daydreams are not decisions. Choose one cup, look inside it carefully, and let the rest evaporate.',
    relationships: 'Idealising a person, or not knowing what you want. Illusions about love. Ask what is real before you commit to the picture.',
    career: 'Scattered focus, tempting offers, a vision without a plan. Pick a direction and test it against reality.',
    reversed: 'Clarity. Choosing at last, seeing through the fantasy, and committing. Or overwhelm that finally forces a decision.',
  },
  'cups-8': {
    description: 'A figure walks away from eight stacked cups under a waning moon, up a rocky path toward mountains. The Eight of Cups is departure, disillusionment and the search for something more.',
    upright: 'It is time to leave. What you built is not nothing, but it is not enough, and you know it. Walk away with dignity and go looking for what is missing.',
    relationships: 'Leaving a relationship that no longer nourishes, or the need for a journey inward. Not every departure is a betrayal.',
    career: 'Quitting a job that is fine and wrong. A search for meaning over security. Take what you learned with you.',
    reversed: 'Staying when you should go, or drifting when you should stay. Fear of change, aimlessness, or a return to what you left. Decide, rather than wander.',
  },
  'cups-9': {
    description: 'A contented figure sits with arms folded before a curved shelf of nine cups. The Nine of Cups is satisfaction, wishes granted and the enjoyment of what you have.',
    upright: 'The wish card. Something you hoped for is arriving. Enjoy comfort, pleasure and gratitude without guilt. You have earned a full shelf.',
    relationships: 'Emotional fulfilment, a happy bond, a wish about love coming true. Contentment, with a small caution against smugness.',
    career: 'Goals achieved, rewards enjoyed, a sense of having arrived. Savour it and share it.',
    reversed: 'Wishes unmet, or met and found hollow. Overindulgence, greed, or the discovery that the thing you wanted was not the thing you needed.',
  },
  'cups-10': {
    description: 'A couple stand arm in arm with children dancing beside them, a rainbow of ten cups arched across the sky above a home. The Ten of Cups is harmony, family and lasting emotional peace.',
    upright: 'The love around you is real and it is enough. Family, chosen or given, brings deep contentment. Cherish these bonds and celebrate what you have made together.',
    relationships: 'A relationship with the foundation to last. Long-term commitment, a home, the start of a family. Shared happiness rather than private happiness.',
    career: 'Colleagues who feel like family, work that leaves room for home, or success that the people you love can share in.',
    reversed: 'Disharmony. A family in conflict, a home that does not feel like one, or a connection you keep reaching for that does not click. Stay kind through the rough patch, and be honest if the fit is simply wrong.',
  },
  'cups-11': {
    description: 'A young figure in a flowered tunic holds a cup from which a fish looks out, the sea behind. The Page of Cups is imagination, sensitivity and a surprising message of the heart.',
    upright: 'Something unexpected and tender arrives. A creative idea, a message of affection, a new feeling you did not plan. Be open, and a little playful.',
    relationships: 'A sweet, shy new attraction, or a message that touches you. Love in its early, curious form.',
    career: 'Creative inspiration, a new idea from an unlikely place, or good news about a project. Follow the fish.',
    reversed: 'Emotional immaturity, escapism, or a creative block. A message that disappoints, or a sensitivity that has become sulking. Grow the feeling up.',
  },
  'cups-12': {
    description: 'A knight on a calm white horse rides slowly with a cup held before him, a river ahead. The Knight of Cups is romance, charm and the pursuit of a feeling.',
    upright: 'A romantic, an invitation, an offer made with feeling. Follow your heart, but keep one eye on whether the offer is more than charm.',
    relationships: 'A proposal, a declaration, a courtship. The classic romantic arrival. Enjoy it and see whether the knight stays past the first river.',
    career: 'A creative offer, diplomacy, or work driven by passion. Charm opens the door; make sure substance walks through it.',
    reversed: 'Moodiness, a promise not kept, or love that is all performance. Disappointment with someone who talks in cups and delivers in air.',
  },
  'cups-13': {
    description: 'A queen on a throne at the water\'s edge gazes into an ornate closed cup. The Queen of Cups is compassion, intuition and emotional depth.',
    upright: 'Lead with empathy. You can hold feeling, yours and others\', without drowning in it. Listen, comfort, and trust what your intuition tells you about people.',
    relationships: 'A deeply caring partner, or the need to be one. Emotional security and understanding. Nurture without losing yourself.',
    career: 'Counselling, caregiving, the arts, or any work where reading people matters. Your sensitivity is a skill.',
    reversed: 'Emotional overwhelm, codependence, or a compassion that has become manipulation. Boundaries dissolving. Refill your own cup first.',
  },
  'cups-14': {
    description: 'A king sits on a throne that floats on a rough sea, calm, a cup in one hand and a sceptre in the other. The King of Cups is emotional mastery, balance and wise counsel.',
    upright: 'Stay calm on rough water. Compassion held together with control. Be the steady one, offer counsel, and let feeling inform you without ruling you.',
    relationships: 'A mature, emotionally steady partner. Diplomacy in conflict, generosity in love. A relationship weathering storms gracefully.',
    career: 'Leadership through emotional intelligence. Mediation, mentoring, calm under pressure. People bring you their problems because you do not panic.',
    reversed: 'Emotion suppressed until it leaks, or used to manipulate. Coldness, moodiness, or a counsellor who cannot take counsel. The sea is inside the throne.',
  },
  // --- Swords: air, mind, conflict, truth ------------------------------------
  'swords-1': {
    description: 'A hand from a cloud holds a sword upright, a crown and laurels at its point, mountains below. The Ace of Swords is clarity, truth and the first cut of a decision.',
    upright: 'The fog lifts and you see it plainly. A breakthrough, a truth spoken, a decision made with a clear mind. Use the edge carefully; it cuts both ways.',
    relationships: 'Honest conversation, clarity about what you want, or a hard truth that clears the air. Better a clean cut than a slow tear.',
    career: 'A new idea with force behind it, a contract, a legal clarity, or the mental sharpness to solve what stumped everyone. Speak plainly.',
    reversed: 'Confusion, a truth twisted, or a clarity that has become cruelty. Clouded judgement and arguments for their own sake. Put the sword down until you can see.',
  },
  'swords-2': {
    description: 'A blindfolded figure sits with two swords crossed over their chest, the sea behind and a sliver of moon above. The Two of Swords is stalemate, a decision refused and the peace of not looking.',
    upright: 'You are holding two things apart and choosing neither. The truce is costing you. Take off the blindfold, look at both, and decide. Not choosing is a choice too.',
    relationships: 'Avoidance, a difficult conversation postponed, or being caught between two people. The silence is not peace.',
    career: 'A decision deferred, two offers weighed forever, or a conflict you refuse to see. Get the information and choose.',
    reversed: 'The blindfold comes off. Information arrives, a stalemate breaks, a choice is made. Or the pressure becomes too much and the swords fall on their own.',
  },
  'swords-3': {
    description: 'Three swords pierce a red heart against a sky of rain. The Three of Swords is heartbreak, grief and the pain of a truth that cuts.',
    upright: 'This hurts, and it is real. Betrayal, loss, or words that wounded. Let the pain be felt rather than argued with. Rain passes; the heart mends around the scar.',
    relationships: 'Heartbreak, a betrayal, a separation. The card does not soften it. What it offers is that the storm is visible and therefore finite.',
    career: 'A painful setback, harsh criticism, or a rift with a colleague. Let it teach you, not define you.',
    reversed: 'Beginning to heal, or refusing to. Forgiveness and release, or a wound kept open by revisiting it. Take the swords out one at a time.',
  },
  'swords-4': {
    description: 'A knight lies in effigy on a tomb, hands in prayer, three swords hung on the wall and one beneath him, a stained window above. The Four of Swords is rest, retreat and recovery.',
    upright: 'Stop. You need rest, and not the kind you take while checking your messages. Withdraw, recover, and let the mind go quiet. The battle will still be there; you will be stronger for it.',
    relationships: 'A pause, a break, or a quiet spell after conflict. Space to recover before deciding anything.',
    career: 'Burnout warning. Take the leave, delegate, and let a project rest before you return with fresh eyes.',
    reversed: 'Restlessness, exhaustion ignored, or a retreat that has become hiding. Either you are refusing rest or refusing to end it. Get up when you are healed, and not before.',
  },
  'swords-5': {
    description: 'A smirking figure gathers three swords while two others walk away, two blades left on the ground. The Five of Swords is conflict won at a cost, and the hollow victory.',
    upright: 'You may win this and lose something larger. Ambition, ego and the need to be right are running ahead of what actually matters. Ask what the swords are worth once everyone has left the field.',
    relationships: 'An argument won by the wrong means. Bullying, humiliation, or the need to be right at the expense of being close. Apologise, or walk away.',
    career: 'Office politics, a backstab, a promotion taken at someone\'s expense. A win that costs the team. Choose your battles and your methods.',
    reversed: 'Reconciliation after conflict, or resentment lingering after a loss. Making amends, or nursing a grudge. Put the swords down and see who is left.',
  },
  'swords-6': {
    description: 'A ferryman poles a boat carrying a huddled woman and child across calm water, six swords standing in the bow. The Six of Swords is transition, passage and the quiet after leaving.',
    upright: 'You are moving on. The crossing is not glamorous, but the water ahead is calmer than the water behind. Carry what you must and let the ferry take you.',
    relationships: 'Leaving a hard situation, or a relationship moving into a calmer phase. Healing that comes from distance.',
    career: 'A move, a change of role, a project put behind you. Progress that feels like escape at first and like relief later.',
    reversed: 'Unable to move on, or a crossing that keeps turning back. Baggage you will not put down, or a change resisted until it becomes worse. Board the boat.',
  },
  'swords-7': {
    description: 'A figure sneaks away from a camp carrying five swords, glancing back, two left behind. The Seven of Swords is stealth, strategy and the theft of a march.',
    upright: 'Not everything is being done in the open. Strategy, cunning, or someone acting alone. Be clever, but ask whether the trick is beneath you, and whether someone is playing one on you.',
    relationships: 'Deception, secrets, or a partner who avoids rather than confronts. Trust needs checking, in both directions.',
    career: 'Competitive tactics, a rival taking credit, or the need to be shrewd. Protect your work. Honesty may not be rewarded, but dishonesty is remembered.',
    reversed: 'The plan exposed, a confession, or the thief caught. Coming clean, or getting caught. Either way, the stealth has ended.',
  },
  'swords-8': {
    description: 'A bound and blindfolded figure stands among eight swords planted in wet ground, a castle behind on a hill. The loops are loose. The Eight of Swords is restriction, mostly self-made.',
    upright: 'You feel trapped, and the trap is made of thoughts. Fear, doubt and old stories have you standing still where you could walk. Test the bindings; they are looser than they feel.',
    relationships: 'Feeling stuck in a bond, or paralysed by fear of losing it. Powerlessness that is largely imagined. Speak, and the ropes loosen.',
    career: 'Believing you cannot leave, cannot ask, cannot change. Victim thinking at work. The exit is behind the blindfold.',
    reversed: 'Release. Seeing the way out, dropping the blindfold, taking the first step. Or a deeper spiral of self-imposed limitation. The choice is the whole card.',
  },
  'swords-9': {
    description: 'A figure sits up in bed with hands over their face, nine swords hanging in the dark above, a quilt of roses and zodiac signs. The Nine of Swords is anxiety, nightmare and the mind at three in the morning.',
    upright: 'Worry is doing you more harm than the thing you worry about. Fear, guilt and sleepless dread. Name the fear in daylight and it shrinks. Ask for help; you are not meant to carry this alone.',
    relationships: 'Anxiety about a relationship, jealousy, or guilt over something said. The dread is bigger than the fact. Talk.',
    career: 'Stress, imposter feelings, fear of failure. The mind is catastrophising. Break the problem into pieces you can hold.',
    reversed: 'The night ending. Hope returning, fears faced and found smaller, or help accepted. Alternatively, despair deepening. Reach for the door.',
  },
  'swords-10': {
    description: 'A figure lies face down with ten swords in their back under a black sky, but the dawn is breaking at the horizon. The Ten of Swords is the end of a cycle, rock bottom, and the certainty that it cannot get worse.',
    upright: 'It is over, and it ended badly. Betrayal, collapse, a painful finish. There is nothing left to fight. That is the mercy in it: the only way from here is up, and the sky is already lightening.',
    relationships: 'A painful ending, a betrayal, or a relationship that has run its full course. Let it be finished.',
    career: 'A failure, a firing, a project killed. Rock bottom. Recovery begins with accepting that this chapter is done.',
    reversed: 'Survival, recovery, and the lesson learned. Rising after a fall. Or a refusal to let the ending end. Pull the swords out and stand up.',
  },
  'swords-11': {
    description: 'A young figure holds a sword upright with both hands on windy high ground, clouds racing behind. The Page of Swords is curiosity, vigilance and a restless mind.',
    upright: 'Ask questions. Curiosity, new ideas and a hunger for truth drive you now. Watch, learn, and speak up. Be quick, but not careless.',
    relationships: 'A talkative new connection, honest words, or a need for mental stimulation. Communication is the theme.',
    career: 'New ideas, research, a fresh perspective. Speak up in the meeting. Beware gossip and half-formed plans.',
    reversed: 'All talk, no substance. Gossip, cynicism, a mind that is sharp and scattered. Hasty words that cut. Think before you speak.',
  },
  'swords-12': {
    description: 'A knight charges headlong on a grey horse with sword raised, trees bent by the wind. The Knight of Swords is ambition, directness and speed of thought turned to action.',
    upright: 'Charge. Determination, sharp thinking and the courage to act on it. Say the thing, make the move. Just remember that a straight line can miss the point.',
    relationships: 'Intense, direct, fast-moving. Attraction that arrives like weather. Watch for coldness once the charge is over.',
    career: 'Ambition, assertiveness, quick decisions. Cut through the noise and act. Take others with you if you can.',
    reversed: 'Aggression without thought. Rushing, bullying, arrogance, or a plan abandoned because it took too long. Rein in the horse.',
  },
  'swords-13': {
    description: 'A queen sits in profile on a throne of clouds, sword upright, one hand raised as if to say enough. The Queen of Swords is clarity, independence and honest judgement.',
    upright: 'See clearly and say it plainly. Experience has made you discerning. Set boundaries, cut through sentiment, and trust your judgement over pleasant fictions.',
    relationships: 'Independence, honesty, and a partner who values truth over comfort. Or the need to stand alone for a while and be all right with it.',
    career: 'Clear communication, fair but firm leadership, and an eye for what is actually going on. Your judgement is trusted.',
    reversed: 'Coldness, bitterness, or judgement that has become cruelty. Isolation dressed as independence. The sword is pointed at the wrong people.',
  },
  'swords-14': {
    description: 'A king sits facing forward on a stone throne, sword slightly tilted, in a clear sky with birds. The King of Swords is intellect, authority and truth held to a standard.',
    upright: 'Think, decide, rule. Logic, ethics and authority are what this moment needs. Be fair and be firm. Your mind is your power here.',
    relationships: 'A partner who values honesty, reason and respect, and may struggle with feeling. Fairness in conflict. Intellect with warmth is the goal.',
    career: 'Law, strategy, senior decision-making. Expertise recognised. Lead by clear thinking and hold the line.',
    reversed: 'Tyranny of the mind. Manipulation, coldness, abuse of authority, or intelligence used to control. The sword has become a weapon instead of a measure.',
  },
  // --- Pentacles: earth, body, money, craft -------------------------------------
  'pentacles-1': {
    description: 'A hand from a cloud offers a golden coin above a garden path leading through an arch to mountains. The Ace of Pentacles is opportunity made tangible: money, health, a seed in good soil.',
    upright: 'A real opportunity, with real ground under it. A job, an investment, a home, a gift. Take it and tend it. Prosperity begins with a single coin planted.',
    relationships: 'A bond with solid foundations, or the practical beginnings of shared life. Security and reliability are attractive here.',
    career: 'A new job, a raise, a business seed with real promise. Say yes to the tangible offer and build on it.',
    reversed: 'A missed opportunity, poor planning, or money slipping through. Something material is unstable. Check the foundation before you build.',
  },
  'pentacles-2': {
    description: 'A figure juggles two coins bound by an infinity loop, ships riding high waves behind. The Two of Pentacles is balance, adaptability and the juggling of priorities.',
    upright: 'You are keeping several things in the air and doing it well, so far. Stay flexible, keep the rhythm, and know when one ball has to be set down.',
    relationships: 'Balancing love with everything else. Time management matters more than grand gestures right now.',
    career: 'Multiple projects, cash flow juggling, adapting to change. Prioritise, and do not mistake motion for progress.',
    reversed: 'Dropping the balls. Overcommitment, financial strain, disorganisation. Simplify before something breaks.',
  },
  'pentacles-3': {
    description: 'A young mason works on a cathedral arch while a monk and an architect consult the plans. The Three of Pentacles is craft, collaboration and skill recognised.',
    upright: 'Good work, done together. Your skill is noticed and your contribution matters. Learn from others, teach what you know, and build something that lasts.',
    relationships: 'A relationship as a joint project, built with care and patience. Teamwork in the home.',
    career: 'Recognition of expertise, teamwork, apprenticeship, a project built to last. Quality is being noticed.',
    reversed: 'Poor workmanship, a team not pulling together, or effort unrecognised. Lack of commitment. Check the plans and the people.',
  },
  'pentacles-4': {
    description: 'A crowned figure sits clutching one coin, another balanced on their head and two beneath their feet, the city behind. The Four of Pentacles is security, control and the fear of losing.',
    upright: 'You are holding on tight. Security matters and there is nothing wrong with saving. But ask what the grip is costing: generosity, movement, the pleasure of what you have.',
    relationships: 'Possessiveness, or a partner who guards their heart like a purse. Control mistaken for care.',
    career: 'Saving, consolidation, caution with money. Sound, up to a point. Hoarding stifles growth.',
    reversed: 'Letting go, or losing control. Generosity released, spending finally, or financial loss through recklessness. The grip loosens one way or another.',
  },
  'pentacles-5': {
    description: 'Two figures, one on crutches, pass through the snow beneath a lit church window. The Five of Pentacles is hardship, loss and the feeling of being left out in the cold.',
    upright: 'Hard times. Money, health or belonging is scarce and you feel abandoned. The window is lit. Help is closer than the snow suggests, if you knock.',
    relationships: 'Feeling alone in a relationship, or a couple weathering poverty together. Isolation. Ask for what you need.',
    career: 'Financial strain, job loss, insecurity. A lean season. Seek support and keep walking toward the light.',
    reversed: 'Recovery from hardship. Doors opening, help accepted, spirits improving. Or the cold prolonged by pride. Go inside.',
  },
  'pentacles-6': {
    description: 'A merchant with scales gives coins to two kneeling beggars. The Six of Pentacles is generosity, charity and the balance of giving and receiving.',
    upright: 'Give, or receive, with grace. Generosity flows and debts are settled. Be mindful of the scales: help that keeps someone kneeling is not help.',
    relationships: 'Support, gifts, and care given freely. Check that the giving goes both ways over time.',
    career: 'A bonus, a mentor\'s help, a charitable cause, or being the one who can afford to give. Share the surplus.',
    reversed: 'Strings attached. Debt, one-sided giving, charity as control, or receiving without gratitude. Rebalance the scales.',
  },
  'pentacles-7': {
    description: 'A farmer leans on a hoe looking at a vine heavy with seven coins, not yet ripe. The Seven of Pentacles is patience, assessment and the long wait before harvest.',
    upright: 'You have worked and the fruit is growing. Not yet. Assess honestly, adjust what needs adjusting, and let time do the part you cannot.',
    relationships: 'A relationship that needs time and tending. Assess whether the investment is bearing fruit, and give it a fair season.',
    career: 'Long-term effort, investment, review. Progress is slow and real. Keep going, and prune what is not producing.',
    reversed: 'Impatience, wasted effort, or a harvest that never came. Frustration with slow returns. Ask whether the vine was ever going to bear, and replant if not.',
  },
  'pentacles-8': {
    description: 'A craftsman carves coin after coin at a bench, six hung finished on the post, a town far off. The Eight of Pentacles is diligence, craft and mastery through repetition.',
    upright: 'Do the work. Skill is built one coin at a time. Focus, practice and care for detail turn labour into mastery. The town can wait.',
    relationships: 'Working on the relationship with steady attention. Small consistent acts over grand promises.',
    career: 'Training, apprenticeship, skill-building, meticulous work. Quality is rewarded. You are becoming very good at this.',
    reversed: 'Perfectionism, drudgery, or corners cut. Work without pride, or pride without progress. Find the meaning in the craft again.',
  },
  'pentacles-9': {
    description: 'A woman in a fine robe stands in a vineyard with a hooded falcon on her hand, nine coins around her. The Nine of Pentacles is self-sufficiency, refinement and earned luxury.',
    upright: 'You built this yourself. Independence, comfort and the quiet pleasure of a life well made. Enjoy the vineyard. You do not need anyone\'s permission.',
    relationships: 'Self-worth first. A relationship that adds to a full life rather than filling an empty one. Independence is attractive.',
    career: 'Financial independence, a business thriving, rewards for discipline. Refined taste and hard-won security.',
    reversed: 'Working for a wealth that does not satisfy, or independence turned to loneliness. Overspending, or a self-worth tied to the vineyard. Hood the falcon and rest.',
  },
  'pentacles-10': {
    description: 'An old man sits with dogs under an archway while a family passes, ten coins arranged in a tree of life. The Ten of Pentacles is legacy, wealth and the security that spans generations.',
    upright: 'Lasting wealth, family stability, inheritance and tradition. What you build now outlives you. Think in generations rather than quarters.',
    relationships: 'A bond with roots: family approval, shared property, a life planned for the long term. Home in the fullest sense.',
    career: 'Established success, a family business, a pension, a legacy. Security that comes from structure.',
    reversed: 'Family conflict over money, a legacy squandered, or security that has become a cage. Tradition weighing too heavily. Ask what the wealth is for.',
  },
  'pentacles-11': {
    description: 'A young figure stands in a green field holding a coin up to study it, mountains far behind. The Page of Pentacles is study, ambition and the beginning of practical mastery.',
    upright: 'A new opportunity to learn or earn. Study, apprentice, plan. You are at the start of something with real material promise, and diligence will carry it.',
    relationships: 'A practical, steady new connection, or a relationship becoming grounded. Small reliable steps.',
    career: 'A new job, a course, a business idea worth researching. Set goals and do the groundwork.',
    reversed: 'Procrastination, a lack of focus, or a plan that stays a plan. Daydreaming about the coin instead of working for it.',
  },
  'pentacles-12': {
    description: 'A knight sits still on a heavy black horse in a ploughed field, holding a coin, going nowhere fast. The Knight of Pentacles is reliability, routine and slow sure progress.',
    upright: 'Steady wins. Do the boring, necessary work and do it thoroughly. You may not be fast, but you will arrive, and what you build will hold.',
    relationships: 'A dependable, loyal partner. Not exciting, deeply reliable. Commitment shown in actions.',
    career: 'Hard work, routine, methodical progress. The employee everyone trusts. Beware only of stagnation.',
    reversed: 'Stuck in routine, boredom, laziness, or stubborn refusal to adapt. The horse has stopped in the field. Move.',
  },
  'pentacles-13': {
    description: 'A queen sits on a throne carved with fruit and goats in a flowering garden, a rabbit at her feet, a coin in her lap. The Queen of Pentacles is nurture, practicality and abundance made homely.',
    upright: 'Care for the body and the home. Practical generosity, warmth, and the ability to make a place feel safe. Provide, and let yourself be provided for.',
    relationships: 'A nurturing, grounded partner and a comfortable home. Love expressed through care and provision.',
    career: 'Business sense joined to kindness. Managing resources, mentoring, creating a productive and humane workplace.',
    reversed: 'Self-neglect through caring for everyone else, or materialism replacing warmth. Smothering, or a home that has become a burden. Tend yourself.',
  },
  'pentacles-14': {
    description: 'A king sits on a throne carved with bulls among vines, a coin in one hand and a sceptre in the other, a castle behind. The King of Pentacles is wealth, mastery and the security of a life built well.',
    upright: 'Prosperity through discipline. You have built something solid and can lead from it. Be generous, be steady, and enjoy what your competence has made.',
    relationships: 'A provider, a protector, a partner who is loyal and practical. Security offered with a steady hand.',
    career: 'Business success, senior leadership, a fortune made or managed. The person who knows how money works. Lead with that knowledge.',
    reversed: 'Greed, stubbornness, or status worshipped for its own sake. Materialism, corruption, or a security so rigid that nothing can grow in it.',
  },
};

/** The guide page for a card, by id. Every card has one; a missing id is a bug caught by tests. */
export function getLore(id: string): Lore {
  const l = LORE[id];
  if (!l) throw new Error(`No lore for ${id}`);
  return l;
}
